### ISSUE TITLE
ValueError when using some of the functions

### ISSUE THREAD

**Issue by FancyBaguette** [Poroknights/librus-apix#15]
I'm encountering a ValueError when calling some of the functions provided - more specifically, get_grades, get_attendance and get_schedule. I'm new to python so lmk if there's some sort of mistake on my side.

## get_grades
Code
```python
from librus_apix.grades import get_grades
grades, average_grades = get_grades(token)

for mark in grades["Mathematics"]:
    print(mark.grade)
```
Result
```
Traceback (most recent call last):
  File "\main.py", line 8, in <module>
    grades, average_grades = get_grades(token)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\librus_apix\grades.py", line 95, in get_grades
    key, value = attr.split(': ')
ValueError: too many values to unpack (expected 2)
```
## get_attendance
Code
```python
from librus_apix.attendance import get_attendance
first_semester, second_semester = get_attendance(token)

for attendance in first_semester:
    print(attendance.symbol, attendance.date)
```
Result
```
Traceback (most recent call last):
  File "\main.py", line 16, in <module>
    first_semester, second_semester = get_attendance(token)
  File "\AppData\Local\Programs\Python\Python310\lib\site-packages\librus_apix\attendance.py", line 63, in get_attendance
    _type, date, lesson, subject, teacher, hour, excursion, by = (
ValueError: not enough values to unpack (expected 8, got 7)
```
## get_schedule
Code
```python
from librus_apix.schedule import get_schedule, schedule_detail
month = '2'
year = '2023'
schedule = get_schedule(token, month, year)
for day in schedule:
  for event in schedule[day]:
    print(event.title)
    prefix, href = event.href.split('/')
    details = schedule_detail(token, prefix, href)
    print(details)
```
Result: Here the code successfully prints out one event from the schedule and then gets the error
```
Zastępstwo z Jan Kowalski na lekcji nr: 5 (Matematyka)
Traceback (most recent call last):
  File "\main.py", line 38, in <module>
    prefix, href = event.href.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by Poroknights** [comment]
## get_grades
The grades variable is dictionary containing the first and the second semester as values. 
Here is how the structure looks like, I hope it is a little bit more clear now.
```py
grades, _ = get_grades(token)
grades = {
    1: {
        "History": list[Grade],
        "Math": list[Grade],
        ...
    },
    2: {
        "History": list[Grade],
        ...
     }

}

```
I have actually updated the example in the README.md now it looks like this
```py
from librus_apix.grades import get_grades

grades, average_grades = get_grades(token)

for semester in grades:
  for mark in grades[semester]["Mathematics"]:
      print(mark.grade)
```
## get_attendance
As for the attendance, it works fine on my side so it might be that different schools have less or more details about the attendance. The exception is raised because I have unpacked the list of the Attendance details as 8 variables thinking it is the same for everyone like so:
```py
 _type, date, lesson, subject, teacher, hour, excursion, by = (
                    i.split(": ")[1].strip()
                    for i in single.attrs["title"]
                    .replace("</b>", "<br>")
                    .replace("<br/>", "")
                    .strip()
                    .split("<br>")
                )
```
It is really messy and causes and error so in my free time I'll work on a fix for that.

## get_schedule
This error is caused by the Event not having an href element which basically means it is not clickable on the Librus site. I will change the example in the README so that it checks if href is present so it won't cause trouble anymore.

```py
# A check for href should be added before working with it.
# If href is not present it is an empty string

for day in schedule:
  for event in schedule[day]:
    print(event.title)
    if href == "":
        continue
    prefix, href = event.href.split('/')
    details = schedule_detail(token, prefix, href)
    print(details)

```

I'm sorry for the trouble with the example I haven't really tested much of it myself and done it on the go without much care. I will try to rewrite it so it is more clear in the free time.

**Comment by Poroknights** [comment]
I have changed the get_attendance to have .attributes value instead of assigning them to separate variables so it won't raise an error that there aren't enough values to unpack any longer. I also included a better examples inside examples directory so it will make things easier to understand. Let me know if there will be any more issues.

**Comment by FancyBaguette** [comment]
Thanks for your hard work. All of the functions work properly now on my side as well
